spring:
  datasource:
    url: jdbc:postgresql://db:5432/Library
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc: lob.non_contextual_creation= true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  data:
    web:
      pageable:
        default-page-size: 10
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
